# 147 LJ particles

units           lj
dimension       3
boundary        s s s
atom_style      atomic

region sbound sphere 0.00 0.00 0.00 25.000 units box side in

# RST_BEGIN
read_data LJ147.geo
# read_restart run_a.rest
# read_restart run_b.rest
# RST_END

include         LJ147.parm
timestep        0.005
run_style       verlet
velocity        all create 0.007 1298371 mom yes rot yes dist gaussian

fix             1 all nvt temp 0.007 0.007 100.0

dump            2 all dcd 100 rlx_0.5_LJ147.dcd
dump_modify  2 unwrap yes

thermo_style    multi
thermo          1000
variable sys_step equal step

fix 5 all wall/region sbound harmonic 1 1 25
compute 1 all gyration

fix Rgave all ave/time 100 5 1000 c_1 file Rg_rlx0.5_LJ147.dat
fix extra all print 1000 "${sys_step}" screen no append steps.dat
dump geometry all atom 1000 dump.atom
dump d0 all image 1000 dump.*.jpg type type
dump_modify d0 pad 10

restart         1000   run_a.rest run_b.rest
run             20000

write_restart         rlx_0.5_LJ147.rest
